
module top (
  inout [14:0]  DDR_addr         ,
  inout [2:0]   DDR_ba           ,
  inout         DDR_cas_n        ,
  inout         DDR_ck_n         ,
  inout         DDR_ck_p         ,
  inout         DDR_cke          ,
  inout         DDR_cs_n         ,
  inout [3:0]   DDR_dm           ,
  inout [31:0]  DDR_dq           ,
  inout [3:0]   DDR_dqs_n        ,
  inout [3:0]   DDR_dqs_p        ,
  inout         DDR_odt          ,
  inout         DDR_ras_n        ,
  inout         DDR_reset_n      ,
  inout         DDR_we_n         ,
  inout         FIXED_IO_ddr_vrn ,
  inout         FIXED_IO_ddr_vrp ,
  inout [53:0]  FIXED_IO_mio     ,
  inout         FIXED_IO_ps_clk  ,
  inout         FIXED_IO_ps_porb ,
  inout         FIXED_IO_ps_srstb,
  
  output [3:0]  vga_r            ,
  output [3:0]  vga_g            ,
  output [3:0]  vga_b            ,
  output        vga_hs           ,
  output        vga_vs             
);

  logic reg_clk;
  logic reg_clk_rstn;
  logic sys_clk;

  zynq_ps u_zynq_ps
  (
    .DDR_addr              (DDR_addr         ),
    .DDR_ba                (DDR_ba           ),
    .DDR_cas_n             (DDR_cas_n        ),
    .DDR_ck_n              (DDR_ck_n         ),
    .DDR_ck_p              (DDR_ck_p         ),
    .DDR_cke               (DDR_cke          ),
    .DDR_cs_n              (DDR_cs_n         ),
    .DDR_dm                (DDR_dm           ),
    .DDR_dq                (DDR_dq           ),
    .DDR_dqs_n             (DDR_dqs_n        ),
    .DDR_dqs_p             (DDR_dqs_p        ),
    .DDR_odt               (DDR_odt          ),
    .DDR_ras_n             (DDR_ras_n        ),
    .DDR_reset_n           (DDR_reset_n      ),
    .DDR_we_n              (DDR_we_n         ),
    
    .FIXED_IO_ddr_vrn      (FIXED_IO_ddr_vrn ),
    .FIXED_IO_ddr_vrp      (FIXED_IO_ddr_vrp ),
    .FIXED_IO_mio          (FIXED_IO_mio     ),
    .FIXED_IO_ps_clk       (FIXED_IO_ps_clk  ),
    .FIXED_IO_ps_porb      (FIXED_IO_ps_porb ),
    .FIXED_IO_ps_srstb     (FIXED_IO_ps_srstb),
    
    .M00_AXI_0_araddr      (),
    .M00_AXI_0_arprot      (),
    .M00_AXI_0_arready     (),
    .M00_AXI_0_arvalid     (),
    .M00_AXI_0_awaddr      (),
    .M00_AXI_0_awprot      (),
    .M00_AXI_0_awready     (),
    .M00_AXI_0_awvalid     (),
    .M00_AXI_0_bready      (),
    .M00_AXI_0_bresp       (),
    .M00_AXI_0_bvalid      (),
    .M00_AXI_0_rdata       (),
    .M00_AXI_0_rready      (),
    .M00_AXI_0_rresp       (),
    .M00_AXI_0_rvalid      (),
    .M00_AXI_0_wdata       (),
    .M00_AXI_0_wready      (),
    .M00_AXI_0_wstrb       (),
    .M00_AXI_0_wvalid      (),
    
    .S_AXI_HP0_0_araddr    (),
    .S_AXI_HP0_0_arburst   (),
    .S_AXI_HP0_0_arcache   (),
    .S_AXI_HP0_0_arid      (),
    .S_AXI_HP0_0_arlen     (),
    .S_AXI_HP0_0_arlock    (),
    .S_AXI_HP0_0_arprot    (),
    .S_AXI_HP0_0_arqos     (),
    .S_AXI_HP0_0_arready   (),
    .S_AXI_HP0_0_arsize    (),
    .S_AXI_HP0_0_arvalid   (),
    .S_AXI_HP0_0_awaddr    (),
    .S_AXI_HP0_0_awburst   (),
    .S_AXI_HP0_0_awcache   (),
    .S_AXI_HP0_0_awid      (),
    .S_AXI_HP0_0_awlen     (),
    .S_AXI_HP0_0_awlock    (),
    .S_AXI_HP0_0_awprot    (),
    .S_AXI_HP0_0_awqos     (),
    .S_AXI_HP0_0_awready   (),
    .S_AXI_HP0_0_awsize    (),
    .S_AXI_HP0_0_awvalid   (),
    .S_AXI_HP0_0_bid       (),
    .S_AXI_HP0_0_bready    (),
    .S_AXI_HP0_0_bresp     (),
    .S_AXI_HP0_0_bvalid    (),
    .S_AXI_HP0_0_rdata     (),
    .S_AXI_HP0_0_rid       (),
    .S_AXI_HP0_0_rlast     (),
    .S_AXI_HP0_0_rready    (),
    .S_AXI_HP0_0_rresp     (),
    .S_AXI_HP0_0_rvalid    (),
    .S_AXI_HP0_0_wdata     (),
    .S_AXI_HP0_0_wid       (),
    .S_AXI_HP0_0_wlast     (),  
    .S_AXI_HP0_0_wready    (),
    .S_AXI_HP0_0_wstrb     (),
    .S_AXI_HP0_0_wvalid    (),
    
    .S_AXI_HP1_0_araddr    (),
    .S_AXI_HP1_0_arburst   (),
    .S_AXI_HP1_0_arcache   (),
    .S_AXI_HP1_0_arid      (),
    .S_AXI_HP1_0_arlen     (),
    .S_AXI_HP1_0_arlock    (),
    .S_AXI_HP1_0_arprot    (),
    .S_AXI_HP1_0_arqos     (),
    .S_AXI_HP1_0_arready   (),
    .S_AXI_HP1_0_arsize    (),
    .S_AXI_HP1_0_arvalid   (),
    .S_AXI_HP1_0_awaddr    (),
    .S_AXI_HP1_0_awburst   (),
    .S_AXI_HP1_0_awcache   (),
    .S_AXI_HP1_0_awid      (),
    .S_AXI_HP1_0_awlen     (),
    .S_AXI_HP1_0_awlock    (),
    .S_AXI_HP1_0_awprot    (),
    .S_AXI_HP1_0_awqos     (),
    .S_AXI_HP1_0_awready   (),
    .S_AXI_HP1_0_awsize    (),
    .S_AXI_HP1_0_awvalid   (),
    .S_AXI_HP1_0_bid       (),
    .S_AXI_HP1_0_bready    (),
    .S_AXI_HP1_0_bresp     (),
    .S_AXI_HP1_0_bvalid    (),
    .S_AXI_HP1_0_rdata     (),
    .S_AXI_HP1_0_rid       (),
    .S_AXI_HP1_0_rlast     (),
    .S_AXI_HP1_0_rready    (),
    .S_AXI_HP1_0_rresp     (),
    .S_AXI_HP1_0_rvalid    (),
    .S_AXI_HP1_0_wdata     (),
    .S_AXI_HP1_0_wid       (),
    .S_AXI_HP1_0_wlast     (),
    .S_AXI_HP1_0_wready    (),
    .S_AXI_HP1_0_wstrb     (),
    .S_AXI_HP1_0_wvalid    (),
    
    .reg_clk               (reg_clk     ),
    .sys_clk               (sys_clk     ),
    .FCLK_RESET0_N_0       (reg_clk_rstn)
    );


endmodule